# [[language]]
# name = "rust"

# [language.config.cargo]
# target = "aarch64-linux-android"
# features = "all"

# [language.config.check]
# command = "clippy"

[language-server.rust-analyzer.config.cargo]
target = "aarch64-linux-android"
features = "all"

[language-server.rust-analyzer.config.check]
command = "clippy"
